[build]
pre_cmd = ["templ generate", "sqlc generate", "(cd tailwind && yarn run tw)"]
cmd = "go build -o ./tmp/main cmd/main.go"
exclude_dir = [
    ".forgejo",
    "docker",
    "storage",
    "tmp",
    "tailwind/node_modules",
    "services/jobs",
]
exclude_regex = [".*_templ.go"]
include_ext = ["go", "templ"]
