stages:
  - test
  - build
  - deploy
  - clean

include:
  - local: .gitlab/_common.gitlab-ci.yml
  - local: .gitlab/_rules.gitlab-ci.yml
  - local: /.gitlab/test.gitlab-ci.yml
  - local: /.gitlab/build.gitlab-ci.yml
  - local: /.gitlab/release.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

secret_detection:
  rules: !reference [.rules:default, rules]

docker_prune:
  rules: !reference [.rules:always, rules]
  stage: clean
  script:
    - docker system prune --force --volumes
