stages:
  - test
  - build
  - deploy

include:
  - local: .gitlab/_common.gitlab-ci.yml
  - local: .gitlab/_rules.gitlab-ci.yml
  - local: /.gitlab/test.gitlab-ci.yml
  - local: /.gitlab/build.gitlab-ci.yml
  - local: /.gitlab/release.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

secret_detection:
  rules: !reference [.rules:default, rules]
  stage: test

container_scanning:
  rules: !reference [.rules:release, rules]
  stage: build
  variables:
    GIT_STRATEGY: fetch
    CS_IMAGE: $CURRENT_IMAGE
    CS_DOCKERFILE_PATH: docker/Dockerfile
