stages:
  - build

variables:
  LATEST_IMAGE: '$CI_REGISTRY_IMAGE:latest'
  GITHUB_REGISTRY: 'ghcr.io/$GITHUB_USER/gobackup'

image: docker:$V_DOCKER-git

.auth_gitlab:
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  after_script:
    - docker logout

.rules:deploy:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

build:
  rules: !reference [.rules:deploy, rules]
  stage: build
  variables:
    DOCKER_BUILDKIT: 1
    CURRENT_IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG'
    GO_CACHE: '$GITHUB_REGISTRY:golang'
    NODE_CACHE: '$GITHUB_REGISTRY:node'
  before_script:
    - !reference [.auth_gitlab, before_script]
  script:
    - apk add bash
    - ./buildx.sh
  after_script:
    - !reference [.auth_gitlab, after_script]
