services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        - DOCKER_VERSION=${DOCKER_VERSION}
        - GOLANG_VERSION=${GOLANG_VERSION}
        - RCLONE_VERSION=${RCLONE_VERSION}
        - RESTIC_VERSION=${RESTIC_VERSION}
    hostname: dev
    command: air -c .air.toml
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=debug
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/flohoss/Documents/:/Users/flohoss/Documents/
