services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        - DOCKER_VERSION=${DOCKER_VERSION}
        - GOLANG_VERSION=${GOLANG_VERSION}
        - RCLONE_VERSION=${RCLONE_VERSION}
        - RESTIC_VERSION=${RESTIC_VERSION}
    hostname: dev
    command: air -c .air.toml
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=debug
      - SWAGGER_HOST=http://localhost:8080
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/flohoss/Documents/:/Users/flohoss/Documents/

  frontend:
    container_name: frontend
    image: node:${NODE_VERSION}-alpine
    working_dir: /web
    command: yarn dev --host
    environment:
      - PUBLIC_API_URL=http://backend:8080/api
    ports:
      - 5173:5173
    volumes:
      - ./web:/web

  node_modules:
    container_name: node_modules
    profiles: [install]
    image: node:${NODE_VERSION}-alpine
    working_dir: /web
    entrypoint: yarn
    volumes:
      - ./web:/web
