// Code generated by "stringer -type=DatabaseType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDatabase-1]
	_ = x[PostgreSQL-2]
	_ = x[MariaDB-3]
}

const _DatabaseType_name = "No DatabasePostgreSQLMariaDB"

var _DatabaseType_index = [...]uint8{0, 11, 21, 28}

func (i DatabaseType) String() string {
	i -= 1
	if i >= DatabaseType(len(_DatabaseType_index)-1) {
		return "DatabaseType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DatabaseType_name[_DatabaseType_index[i]:_DatabaseType_index[i+1]]
}
