// Code generated by "stringer -type=RepositoryType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Local-1]
	_ = x[Rclone-2]
}

const _RepositoryType_name = "LocalRclone"

var _RepositoryType_index = [...]uint8{0, 5, 11}

func (i RepositoryType) String() string {
	i -= 1
	if i >= RepositoryType(len(_RepositoryType_index)-1) {
		return "RepositoryType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RepositoryType_name[_RepositoryType_index[i]:_RepositoryType_index[i+1]]
}
