CREATE TABLE IF NOT EXISTS
    jobs (name TEXT PRIMARY KEY, cron TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS
    runs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        job TEXT NOT NULL,
        start_time DATETIME NOT NULL,
        end_time DATETIME,
        status TEXT NOT NULL,
        FOREIGN KEY (job) REFERENCES jobs (name) ON DELETE RESTRICT ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS
    logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        run_id INTEGER NOT NULL,
        severity TEXT NOT NULL,
        message TEXT NOT NULL,
        created_at DATETIME NOT NULL,
        FOREIGN KEY (run_id) REFERENCES runs (id) ON DELETE RESTRICT ON UPDATE CASCADE
    );