variables:
  LATEST_IMAGE: '$CI_REGISTRY_IMAGE:latest'
  GITHUB_REGISTRY: 'ghcr.io/$GITHUB_USER/gobackup'

image: docker:$V_DOCKER-git

.login_registry:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  cache:
    paths:
      - .go/pkg/mod/
