variables:
  GITHUB_REGISTRY: 'ghcr.io/$GITHUB_USER/gobackup'
  DOCKER_VERSION: '24.0.4'
  GOLANG_VERSION: '1.20'
  NODE_VERSION: 'lts'
  ALPINE_VERSION: '3'
  RCLONE_VERSION: '1.63.1'
  RESTIC_VERSION: '0.15.2'
  DEBIAN_VERSION: '12'
  TELEPORT_VERSION: '13.2.3'

image: docker:$DOCKER_VERSION-git

.login_registry:
  before_script:
    - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  cache:
    paths:
      - .go/pkg/mod/
