build:
  rules: !reference [.rules:release, rules]
  stage: build
  extends: .login_registry
  services:
    - name: docker:$V_DOCKER-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_BUILDKIT: '1'
    CURRENT_IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG'
    GO_CACHE: '$GITHUB_REGISTRY:golang'
    NODE_CACHE: '$GITHUB_REGISTRY:node'
  script:
    - apk add bash
    - .gitlab/buildx.sh
