build_release:
  rules: !reference [.rules:release, rules]
  stage: build
  extends: .login_registry
  services:
    - name: docker:$DOCKER_VERSION-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_BUILDKIT: '1'
    LATEST_IMAGE: '$GITHUB_REGISTRY:latest'
    CURRENT_IMAGE: '$GITHUB_REGISTRY:$CI_COMMIT_TAG'
    GO_CACHE: '$GITHUB_REGISTRY:cache-golang'
    NODE_CACHE: '$GITHUB_REGISTRY:cache-node'
    RESTIC_CACHE: '$GITHUB_REGISTRY:cache-restic'
  script:
    - apk add bash
    - .gitlab/buildx.sh
