defaults:
  cron: '0 3 * * 0'
  envs:
    - key: SLEEP_TIME
      value: '5'
  healthcheck:
    start:
      - url: http://localhost:8080
      - params: { 'foo': 'bar' }

jobs:
  - name: Example
    cron: '0 5 * * 0'
    commands:
      - command: ls -la
      - command: sleep ${{ SLEEP_TIME }}
      - command: echo "Done!"
      - command: sleep ${{ SLEEP_TIME }}
  - name: Example
    commands:
      - command: ls -la
      - command: sleep ${{ SLEEP_TIME }}
      - command: echo "Done!"
      - command: sleep ${{ SLEEP_TIME }}
