defaults:
  cron: '0 3 * * 0'
  envs:
    - key: SLEEP_TIME
      value: '5'

healthcheck:
  authorization: 'Bearer ${{ HEALTHCHECK_AUTH_TOKEN }}'
  type: 'POST'
  start:
    url: http://localhost:8080
    params:
      success: true
    body: '{"foo": "bar"}'
  end:
    url: http://localhost:8080
    params:
      success: true
    body: '{"foo": "bar"}'
  failure:
    url: http://localhost:8080
    params:
      success: false
      error: 'Backup failed'
    body: '{"foo": "bar"}'

jobs:
  - name: Example
    cron: '0 5 * * 0'
    commands:
      - command: ls -la
      - command: sleep ${{ SLEEP_TIME }}
      - command: echo "Done!"
      - command: sleep ${{ SLEEP_TIME }}
  - name: Example
    commands:
      - command: ls -la
      - command: sleep ${{ SLEEP_TIME }}
      - command: echo "Done!"
      - command: sleep ${{ SLEEP_TIME }}
