defaults:
  cron: '0 3 * * *'
  envs:
    - key: RESTIC_PASSWORD_FILE
      value: /secrets/.resticpwd
    - key: TEMP
      value: '-l -a'

jobs:
  - name: Test
    envs:
      - key: RESTIC_REPOSITORY
        value: rclone:pcloud:Server/Backups/directus
    commands:
      - command: ls -la
        file_output: /tmp/ls.txt
      - command: ls $TEMP
