defaults:
  cron: '0 3 * * *'
  envs:
    - key: RESTIC_PASSWORD_FILE
      value: '/secrets/.resticpwd'
    - key: BASE_REPOSITORY
      value: 'rclone:pcloud:Server/Backups'
    - key: APPDATA_PATH
      value: '/mnt/user/appdata'

jobs:
  - name: Cleanup
    cron: '0 5 * * 0'
    envs:
      - key: RESTIC_POLICY
        value: '--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75'
      - key: RESTIC_POLICY_SHORT
        value: '--keep-last 7'
    commands:
      - command: restic -r ${BASE_REPOSITORY}/directus unlock
      - command: restic -r ${BASE_REPOSITORY}/forgejo unlock
      - command: restic -r ${BASE_REPOSITORY}/kanidm unlock
      - command: restic -r ${BASE_REPOSITORY}/media unlock
      - command: restic -r ${BASE_REPOSITORY}/paperless unlock
      - command: restic -r ${BASE_REPOSITORY}/godash unlock
      - command: restic -r ${BASE_REPOSITORY}/synapse unlock
      - command: restic -r ${BASE_REPOSITORY}/traefik unlock
      - command: restic -r ${BASE_REPOSITORY}/unraid-boot unlock
      - command: restic -r ${BASE_REPOSITORY}/vaultwarden unlock
      - command: restic -r ${BASE_REPOSITORY}/icloud unlock
      - command: restic -r ${BASE_REPOSITORY}/directus forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/forgejo forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/kanidm forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/media forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/paperless forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/godash forget ${RESTIC_POLICY_SHORT} --prune
      - command: restic -r ${BASE_REPOSITORY}/synapse forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/traefik forget ${RESTIC_POLICY_SHORT} --prune
      - command: restic -r ${BASE_REPOSITORY}/unraid-boot forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/vaultwarden forget ${RESTIC_POLICY} --prune
      - command: restic -r ${BASE_REPOSITORY}/icloud forget ${RESTIC_POLICY} --prune
  - name: Directus
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/directus
    commands:
      - command: restic backup ${APPDATA_PATH}/directus
  - name: Forgejo
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/forgejo
    commands:
      - command: docker exec -e PASSWORD=password forgejo-db pg_dump db --username=user
        file_output: ${APPDATA_PATH}/forgejo/.dbBackup.sql
      - command: restic backup ${APPDATA_PATH}/forgejo
  - name: Nextcloud
    commands:
      - command: rclone sync --multi-thread-streams=1 /mnt/user/nextcloud-backup pcloud:Server/Backups/nextcloud-aio
  - name: Kanidm
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/kanidm
    commands:
      - command: restic backup ${APPDATA_PATH}/kanidm
  - name: Media
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/media
    commands:
      - command: restic backup ${APPDATA_PATH}/media
  - name: Paperless
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/paperless
    commands:
      - command: docker exec paperless document_exporter ${APPDATA_PATH}/paperless/export
        file_output: ${APPDATA_PATH}/paperless/.export.log
      - command: restic backup ${APPDATA_PATH}/paperless
  - name: GoDash
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/godash
    commands:
      - command: restic backup ${APPDATA_PATH}/godash
  - name: Matrix
    envs:
      - key:  RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/synapse
    commands:
      - command: docker exec -e PASSWORD=password matrix-db pg_dumpall --username=postgres
        file_output: ${APPDATA_PATH}/synapse/.dbBackup.sql
      - command: restic backup ${APPDATA_PATH}/synapse
  - name: Traefik
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/traefik
    commands:
      - command: restic backup ${APPDATA_PATH}/traefik
  - name: Unraid Boot
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/unraid-boot
    commands:
      - command: restic backup /unraid/boot
  - name: Vaultwarden
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/vaultwarden
    commands:
      - command: restic backup ${APPDATA_PATH}/vaultwarden
  - name: iCloud
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/icloud
    commands:
      - command: restic backup ${APPDATA_PATH}/icloud
  - name: iCloud - Data
    envs:
      - key: RESTIC_REPOSITORY
        value: ${BASE_REPOSITORY}/icloud-data
    commands:
      - command: restic backup /mnt/user/icloud
