// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: logs.sql

package jobs

import (
	"context"
	"strings"
)

const createLog = `-- name: CreateLog :one
INSERT INTO
    logs (created_at, run_id, severity_id, message)
VALUES
    (?, ?, ?, ?) RETURNING created_at, run_id, severity_id, message
`

type CreateLogParams struct {
	CreatedAt  int64  `json:"created_at"`
	RunID      int64  `json:"run_id"`
	SeverityID int64  `json:"severity_id"`
	Message    string `json:"message"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.CreatedAt,
		arg.RunID,
		arg.SeverityID,
		arg.Message,
	)
	var i Log
	err := row.Scan(
		&i.CreatedAt,
		&i.RunID,
		&i.SeverityID,
		&i.Message,
	)
	return i, err
}

const listLogsByRunIDs = `-- name: ListLogsByRunIDs :many
SELECT
    created_at,
    run_id,
    severity_id,
    message,
    STRFTIME(
        '%Y-%m-%d %H:%M:%S',
        created_at / 1000,
        'unixepoch',
        'localtime'
    ) AS created_at_time
FROM
    logs
WHERE
    run_id IN (/*SLICE:run_ids*/?)
ORDER BY
    run_id,
    created_at
`

type ListLogsByRunIDsRow struct {
	CreatedAt     int64       `json:"created_at"`
	RunID         int64       `json:"run_id"`
	SeverityID    int64       `json:"severity_id"`
	Message       string      `json:"message"`
	CreatedAtTime interface{} `json:"created_at_time"`
}

func (q *Queries) ListLogsByRunIDs(ctx context.Context, runIds []int64) ([]ListLogsByRunIDsRow, error) {
	query := listLogsByRunIDs
	var queryParams []interface{}
	if len(runIds) > 0 {
		for _, v := range runIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:run_ids*/?", strings.Repeat(",?", len(runIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:run_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogsByRunIDsRow
	for rows.Next() {
		var i ListLogsByRunIDsRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.RunID,
			&i.SeverityID,
			&i.Message,
			&i.CreatedAtTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
