// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: logs.sql

package jobs

import (
	"context"
)

const createLog = `-- name: CreateLog :one
INSERT INTO
    logs (run_id, severity_id, message)
VALUES
    (?, ?, ?) RETURNING id, run_id, severity_id, message, created_at
`

type CreateLogParams struct {
	RunID      int64  `json:"run_id"`
	SeverityID int64  `json:"severity_id"`
	Message    string `json:"message"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog, arg.RunID, arg.SeverityID, arg.Message)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.SeverityID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listLogs = `-- name: ListLogs :many
SELECT
    id, run_id, severity_id, message, created_at
FROM
    logs
WHERE
    run_id = ?
ORDER BY
    created_at DESC
`

func (q *Queries) ListLogs(ctx context.Context, runID int64) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.SeverityID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
