// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package jobs

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Command struct {
	ID      uuid.UUID `json:"id"`
	JobID   string    `json:"job_id"`
	Command string    `json:"command"`
}

type Env struct {
	ID    uuid.UUID `json:"id"`
	JobID string    `json:"job_id"`
	Key   string    `json:"key"`
	Value string    `json:"value"`
}

type Job struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Cron string `json:"cron"`
}

type Log struct {
	ID         int64     `json:"id"`
	RunID      int64     `json:"run_id"`
	SeverityID int64     `json:"severity_id"`
	Message    string    `json:"message"`
	CreatedAt  time.Time `json:"created_at"`
}

type Run struct {
	ID        int64        `json:"id"`
	JobID     string       `json:"job_id"`
	StatusID  int64        `json:"status_id"`
	StartTime time.Time    `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type RunsView struct {
	ID        int64  `json:"id"`
	JobID     string `json:"job_id"`
	StatusID  int64  `json:"status_id"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	Duration  string `json:"duration"`
}

type Severity struct {
	ID       int64  `json:"id"`
	Severity string `json:"severity"`
}

type Status struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}
