// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package jobs

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Command struct {
	ID      uuid.UUID `json:"id"`
	JobID   string    `json:"job_id"`
	Command string    `json:"command"`
}

type Env struct {
	ID    uuid.UUID `json:"id"`
	JobID string    `json:"job_id"`
	Key   string    `json:"key"`
	Value string    `json:"value"`
}

type Job struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Cron string `json:"cron"`
}

type JobsView struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Cron         string         `json:"cron"`
	RunStatusID  sql.NullInt64  `json:"run_status_id"`
	RunStartTime sql.NullString `json:"run_start_time"`
	RunEndTime   sql.NullString `json:"run_end_time"`
	RunDuration  sql.NullString `json:"run_duration"`
}

type Log struct {
	CreatedAt  int64  `json:"created_at"`
	RunID      int64  `json:"run_id"`
	SeverityID int64  `json:"severity_id"`
	Message    string `json:"message"`
}

type Run struct {
	ID        int64        `json:"id"`
	JobID     string       `json:"job_id"`
	StatusID  int64        `json:"status_id"`
	StartTime time.Time    `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type RunsView struct {
	ID        int64          `json:"id"`
	JobID     string         `json:"job_id"`
	StatusID  int64          `json:"status_id"`
	StartTime sql.NullString `json:"start_time"`
	EndTime   sql.NullString `json:"end_time"`
	Duration  sql.NullString `json:"duration"`
	Logs      interface{}    `json:"logs"`
}

type Severity struct {
	ID       int64  `json:"id"`
	Severity string `json:"severity"`
}

type Status struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}
