// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package jobs

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO
    jobs (name, cron)
VALUES
    (?, ?) ON CONFLICT (name) DO
UPDATE
SET
    cron = EXCLUDED.cron RETURNING name, cron
`

type CreateJobParams struct {
	Name string `json:"name"`
	Cron string `json:"cron"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.Name, arg.Cron)
	var i Job
	err := row.Scan(&i.Name, &i.Cron)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE
    name = ?
`

func (q *Queries) DeleteJob(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, name)
	return err
}

const getJob = `-- name: GetJob :one
SELECT
    name, cron
FROM
    jobs
WHERE
    name = ?
`

func (q *Queries) GetJob(ctx context.Context, name string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, name)
	var i Job
	err := row.Scan(&i.Name, &i.Cron)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT
    name, cron
FROM
    jobs
ORDER BY
    name
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(&i.Name, &i.Cron); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :exec
UPDATE jobs
SET
    cron = ?
WHERE
    name = ?
`

type UpdateJobParams struct {
	Cron string `json:"cron"`
	Name string `json:"name"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob, arg.Cron, arg.Name)
	return err
}
