// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema.sql

package jobs

import (
	"context"
)

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT
  version
FROM
  schema_version
LIMIT
  1
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const setSchemaVersion = `-- name: SetSchemaVersion :exec
INSERT
OR IGNORE INTO schema_version (version)
VALUES
  (?)
`

func (q *Queries) SetSchemaVersion(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, setSchemaVersion, version)
	return err
}
