// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package jobs

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (jti, subject, created_at, expires_at, revoked)
VALUES (?, ?, ?, ?, 0)
`

type CreateSessionParams struct {
	Jti       string `json:"jti"`
	Subject   string `json:"subject"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.Jti,
		arg.Subject,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE
  expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
  jti,
  subject,
  created_at,
  expires_at,
  revoked
FROM
  sessions
WHERE
  jti = ?
  AND revoked = 0
  AND expires_at > ?
`

type GetActiveSessionParams struct {
	Jti       string `json:"jti"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveSession, arg.Jti, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Jti,
		&i.Subject,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET
  revoked = 1
WHERE
  jti = ?
`

func (q *Queries) RevokeSession(ctx context.Context, jti string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, jti)
	return err
}
