// Code generated by "stringer -type=JobStatus"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[New-0]
	_ = x[Running-1]
	_ = x[Stopped-2]
	_ = x[Success-3]
}

const _JobStatus_name = "NewRunningStoppedSuccess"

var _JobStatus_index = [...]uint8{0, 3, 10, 17, 24}

func (i JobStatus) String() string {
	if i >= JobStatus(len(_JobStatus_index)-1) {
		return "JobStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
