// Code generated by "stringer -type=LogType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Info-1]
	_ = x[Warn-2]
	_ = x[Error-3]
}

const _LogType_name = "infowarnerror"

var _LogType_index = [...]uint8{0, 4, 8, 13}

func (i LogType) String() string {
	i -= 1
	if i >= LogType(len(_LogType_index)-1) {
		return "LogType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogType_name[_LogType_index[i]:_LogType_index[i+1]]
}
