// Code generated by "stringer -type=LogTopic"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Backup-1]
	_ = x[Restic-2]
	_ = x[Docker-3]
	_ = x[Database-4]
}

const _LogTopic_name = "BackupResticDockerDatabase"

var _LogTopic_index = [...]uint8{0, 6, 12, 18, 26}

func (i LogTopic) String() string {
	i -= 1
	if i >= LogTopic(len(_LogTopic_index)-1) {
		return "LogTopic(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogTopic_name[_LogTopic_index[i]:_LogTopic_index[i+1]]
}
